feat(player): add react-youtube test page
mash-up-kr/muzily-web pull request #20
Opened 2022-06-29 13:43 UTC by Young-mason

ISSUES CLOSED: #2

### Issue Number

close: #

### 작업 내역
<img width="401" alt="image" src="https://user-images.githubusercontent.com/61150435/176450282-8d4a2910-55f1-4041-b97c-dacb80ae000c.png">

- [x] react-youtube 를 이용한 간단한 플레이어 구현
- [x] 재생, 정지, 다음, 이전, 숨기기 버튼 
- [x] 재생 끝났을때 다음곡으로 이동하는 기능 추가

### 변경사항

- @type/react-youtube 제거: react-youtube에 타입이 이미 내장되어있다고 함

### PR 특이 사항
 
- 간단히 하드코딩한 mock 데이터로 작업하였습니다.
- 작동 테스트를 위해 디자인은 최소화한 상태 이므로 작동 여부에 포커스 바랍니다
- 모바일 환경에서 여러 문제들이 발견됐는데 별도의 이슈로 관리할게요!

### Checklist

> PR 등록 전 확인할 점

- [ ] PR 제목은 포맷과 내용 둘 다 알맞게 작성되었는가 (e.g., `feat(user): add login page`)
- [ ] assignee가 본인으로 되어있고, label은 PR 주제에 맞게 추가했는가
- [ ] description에 PR에 대해 구체적으로 설명했는가

2022-06-29 23:33 UTC, kor-Chipmunk approved these changes
LGTM 입니다!
그나저나 찾아보니 모바일 일 때는 불필요한 데이터 누수를 막기 위해 자동 재생을 지원하지 않는다고 하네요..! ( [링크](https://developers.google.com/youtube/iframe_api_reference#Mobile_considerations) )
방장 환경은 무조건 PC 로만 고정해야하는걸까요?

![스크린샷 2022-06-30 오전 8 17 21](https://user-images.githubusercontent.com/16275188/176561411-b4a7dcf4-c65a-4511-a2a4-bf4a11325881.png)

2022-06-30 05:20 UTC, Young-mason commented
맞아 그래서 우회해보려고 런타임에서 버튼 클릭하는 스크립트도 짜보고 했는데, 모바일에서는 전혀 동작안하네.. 🥲
pc에서는 동작하니 mvp는 방장환경을 pc로 가져가는쪽으로 얘기해보고, 모바일에서 어떻게 할지는 계속 방법을 찾아바야될듯

2022-06-30 14:07 UTC, swimjiy approved these changes
LGTM👍 모바일에서 자동재생 적용 안되는 이슈는 나도 잠깐 시도해봤는데 잘 안되네ㅠ 추가로 확인해보고 찾음 공유할게!

2022-07-04 02:43 UTC, manudeli requested changes
@Young-mason  suggestion code 남겨놨어

한번 보고 괜찮으면 commit suggestion 받아주세용~

2022-07-04 02:43 UTC, manudeli commented on pages/play-test/index.tsx
>            onReady={(event) => setPlayer(event.target)}
```suggestion
          onReady={(event) => {
            setPlayer(event.target);
            event.target.playVideo();
          }}
```

2022-07-04 02:43 UTC, manudeli commented on pages/play-test/index.tsx
>            onReady={(event) => setPlayer(event.target)}
이렇게 변경하면 모바일에서도 잘 자동재생 될거야ㅎㅎ
재생중인 id가 바뀌면 iframe을 다 다시 받아오니까 player의 인스턴스가 변경되니까 handleChangeNext에서 player.playVideo() 하면 안되는 문제라고 생각되네~ 그래서 onReady일 때 player가 playVideo되도록 써봤어

@Young-mason 아래는 모바일 사이즈에서 테스트 한거 한번 저렇게 commit suggestion 받고 한번 테스트 해봐줄 수 있어?
![chrome-capture-2022-6-4](https://user-images.githubusercontent.com/61593290/177071744-e41dc0bd-5e2a-43cc-ace3-8c25940e7506.gif)
t

2022-07-04 02:43 UTC, manudeli commented on pages/play-test/index.tsx
> +
```suggestion
{player ? (
        <div style={{ display: "flex", marginBottom: "1em" }}>
          <button type="button" onClick={() => player.seekTo(120, true)}>
            2분 0초 이동
          </button>

          <button id="play" type="button" onClick={() => player.playVideo()}>
            재생
          </button>
          <button type="button" onClick={() => player.pauseVideo()}>
            정지
          </button>
          <button type="button" onClick={handleChangeNext}>
            다음
          </button>
          <button type="button" onClick={handleChangePrev}>
            이전
          </button>
          <button type="button" onClick={() => setHidden((prev) => !prev)}>
            {hidden ? "보이기" : "숨기기"}
          </button>
        </div>
      ) : (
        <div>loading...</div>
      )}
```

2022-07-04 02:43 UTC, manudeli commented on pages/play-test/index.tsx
> +
player가 ready가 되기전에 클릭이 되지 않도록 loading처리해서 player의 메소드를 사용할 때 optional chaning을 제거 해주면 더 좋을 것 같아

2022-07-04 03:24 UTC, manudeli commented on pages/play-test/index.tsx
>            onReady={(event) => setPlayer(event.target)}
이거 넣으면 iOS도 잘 될때도 있고 안될때도 있네 원인은 아래 런타임 에러때문인거 같아

```typescript
useEffect(() => {
    if (player.current) {
      player.current.playVideo();
    }
  }, [player.current]);
```
<img width="790" alt="image" src="https://user-images.githubusercontent.com/61593290/177076173-386c7d62-d5b8-4651-bc34-f0acadb3df71.png">

2022-07-04 03:25 UTC, manudeli commented on pages/play-test/index.tsx
>            onReady={(event) => setPlayer(event.target)}
iOS에서 콘솔열고 테스트 필요해보영~! 파링파링 이것만 해결되면 공수 절반이다이~

2022-07-04 08:56 UTC, kor-Chipmunk commented on pages/play-test/index.tsx
>            onReady={(event) => setPlayer(event.target)}
@manudeli 오.. 혹시 PC 에서 모바일환경처럼 개발자도구 열고 어떻게 테스트해볼 수 있나요?

2022-07-04 09:16 UTC, manudeli commented on pages/play-test/index.tsx
>            onReady={(event) => setPlayer(event.target)}
@kor-Chipmunk 선재 이거 물어보는 거 맞을까요?

iOS simulator safari debug
https://raniee.tistory.com/21

2022-07-04 09:33 UTC, kor-Chipmunk commented on pages/play-test/index.tsx
>            onReady={(event) => setPlayer(event.target)}
@manudeli 오, 감사합니당

2022-07-04 22:29 UTC, Young-mason commented on pages/play-test/index.tsx
> +
요 커밋은 commit suggestion은 resolve가 안되는군 .. 🤔

2022-07-06 13:25 UTC, manudeli approved these changes

2022-07-07 09:14 UTC, merged