feat(thumbnail): next 서버에서  썸네일 대표색상 추출하는 기능 추가
mash-up-kr/muzily-web pull request #44
Opened 2022-07-18 14:24 UTC by Young-mason

서버사이드에서 썸네일 추출 기능 추가
 재생중 화면 기능 추가

### Issue Number

close: #25 

### 작업 내역

> 구현 내용 및 작업 했던 내역

localhost:3000/rooms/123 에서 테스트 가능

- [x] ssr로 썸네일 추출하는 기능 추가
- [x] 재생중 화면 개선

### 변경사항

- 의존성 목록
  - node-vibrant  

### PR 특이 사항

#43 썸네일 컬러 뽑아내는 기능관련 이슈 공유

### Checklist

> PR 등록 전 확인할 점

- [ ] PR 제목은 포맷과 내용 둘 다 알맞게 작성되었는가 (e.g., `feat(user): add login page`)
- [ ] assignee가 본인으로 되어있고, label은 PR 주제에 맞게 추가했는가
- [ ] description에 PR에 대해 구체적으로 설명했는가

2022-07-20 04:08 UTC, manudeli requested changes
테스트 해봤는데 잘 되더라~!

코드 일관성, 타이핑에서 조금만 더 수정을 요청해볼게!

2022-07-20 04:08 UTC, manudeli commented on pages/rooms/[roomId]/index.tsx
> +          videoList={MUSIC_LIST}
```suggestion
          musicList={MUSIC_LIST}
```
혹은
```suggestion
          videoList={VIDEO_LIST}
```
로 통일 필요해보여~! 근데 어쨌든 우리는 video에서 음악을 들고 오는 거니까 videoList가 맞지 않을까 싶네

2022-07-20 04:08 UTC, manudeli commented on pages/rooms/[roomId]/index.tsx
> +  );
trycatch로 예외처리 해주면 더 좋겠다

2022-07-20 04:08 UTC, manudeli commented on pages/rooms/[roomId]/index.tsx
> +    thumbnail: "https://i.ytimg.com/vi/DYrY1E4-9NI/hqdefault.jpg",
thumbnail은 getInitialProps에서 id를 기준으로 url을 넣어주는 걸로 처리해서 반복을 줄이고 유지보수하거나 데이터를 저장할 때 최소화 할 수 있겠다~

```typescript
MUSIC_LIST.map(({ id, artist, title }) => ({
  id,
  artist,
  title,
  thumbnail: `https://i.ytimg.com/vi/${id}/hqdefault.jpg`
}))
```

아니면 혹시 YouTube API의 응답이 이런 형태로 오는 건가??

2022-07-20 04:08 UTC, manudeli commented on components/domains/NowPlayingCard/index.tsx
>  const StyledContainer = styled.div<{ noPlaylist?: boolean }>`
1. components/uis 안에 있는 Spacer를 사용할 수 있는 부분은 변경해보면 어떨까? Container, Wrapper, Content에 공통된 컴포넌트를 사용할 수 있다면 아마 다른 누가 보더라도 css를 자세히 보지 않더라도 확실히 알거 같아

2. 다른 기능없이 styled만 하는 컴포넌트는 <S.Container /> 형태로 오도록 하는 컨벤션을 사용해보면 좋을 거 같아
```typescript
const S = {
  MusicText: styled.div`
  color: #fff;
  z-index: 1;
  position: absolute;
  font-weight: 600;
  font-size: 17px;
  line-height: 145%;
  letter-spacing: -0.544648px;
  /* white-space: nowrap; */
  left: 0;
  bottom: 0;
  width: 100%;
  /* max-height: 75px; */
  padding: 0 20px;
  bottom: 30px;
  display: -webkit-box;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;
  overflow: hidden;
  text-overflow: ellipsis;
` 
}
```

예를 들면 이런 식으로! 나중에 공통 컴포넌트로 묶어야 할 때 투두리스트 처럼 찾기 쉽게 되어서 좋더라구

2022-07-20 04:08 UTC, manudeli commented on pages/rooms/[roomId]/index.tsx
> +    data,
data보다 명확한 네이밍이 되면 더 좋을 거 같아

2022-07-20 04:08 UTC, manudeli commented on types/musics/index.ts
> +  colors: (string | undefined)[];
```suggestion
  colors: string[];
```

getInitialProps에서 애초에 colors에 컬러를 추가해준다면 불필요한 union을 없애서 if문을 줄일 수 있을 거 같아

2022-07-20 04:08 UTC, manudeli commented on pages/rooms/[roomId]/index.tsx
> +    })
너무 좋다... 이거 나도 써봐야겠따 진짜 좋네

2022-07-20 05:08 UTC, swimjiy reviewed
컬러 들어가니까 너무 예쁘다 고생 많았어!
다른건 종현이가 꼼꼼하게 확인해준 것 같아서 통일성 관련해서만 코멘트 하나 남겼습니다👍

2022-07-20 05:08 UTC, swimjiy commented on pages/rooms/[roomId]/index.tsx
> +const RoomPage: NextPage<RoomPageProps> = (props) => {
요기 `(props)` 가 `({ data })` 이렇게 destructuring 해주면 어떤 props가 들어오는지 바로 확인할 수 있어 좋을 것 같아~ 다른 컴포넌트들은 다 그렇게 작업해준 것 같은데 요 페이지만 그런듯!

2022-07-21 10:48 UTC, Young-mason commented on pages/rooms/[roomId]/index.tsx
> +const RoomPage: NextPage<RoomPageProps> = (props) => {
가끔 요 데이터는 props에서 가져온다는걸 명시적으로 표현하고 싶을때 destructuring을 안하는 경우도 있던거같아!  

근데 요 케이스는 습관적으로 props를 쓴거같긴하당 ㅋㅋㅋ 통일감있게 destruction 적용 해놓을게!

2022-07-21 10:50 UTC, Young-mason commented on pages/rooms/[roomId]/index.tsx
> +    thumbnail: "https://i.ytimg.com/vi/DYrY1E4-9NI/hqdefault.jpg",
더미데이터라 크게 신경을 안썻당 ㅋㅋ 아직 응답형태에 대한 정의가 없어서 요건 백엔드 api 연동하면서 챙겨볼게!

2022-07-21 10:59 UTC, Young-mason commented on components/domains/NowPlayingCard/index.tsx
>  const StyledContainer = styled.div<{ noPlaylist?: boolean }>`
오오 좋당 1번 Spacer 적용할 수있는 부분은 적용하고 기존에 올라갔던 부분에서도 수정해볼게~!
2번 아이디어도 넘 좋구만! 👍 가독성도 괜찮고 키값으로 바로 찾을수있게 되서 사용하기 편할듯

2022-07-21 11:17 UTC, manudeli approved these changes
리뷰 반영 감사요!

2022-07-23 08:45 UTC, merged