Feat: 메인 인트로 UI / 로그인 UI 추가합니다.
mash-up-kr/muzily-web pull request #62
Opened 2022-07-28 13:39 UTC by kor-Chipmunk

### Issue Number

close: #54 #55 

### 작업 내역

> 구현 내용 및 작업 했던 내역

- [x] 메인 인트로 UI
- [x] 로그인 인트로 UI

### 변경사항

- 카카오 로그인 버튼 기본 텍스트 삭제
- 카카오 로그인 이미지로 대체

### 참고사항

메인 인트로 아래, 무한히 옆으로 움직이는 배너(?) 컴포넌트는 추후 작업합니다.
[flicking](https://www.npmjs.com/package/@egjs/react-flicking) 라이브러리 참고하겠습니다. ㅎ.ㅎ
( 참고 아래 사진 )

![스크린샷 2022-07-28 오후 10 38 43](https://user-images.githubusercontent.com/16275188/181519213-2c0c12b1-d03d-4fb6-9951-ba5a29995190.png)

### Checklist

> PR 등록 전 확인할 점

- [x] PR 제목은 포맷과 내용 둘 다 알맞게 작성되었는가 (e.g., `feat(user): add login page`)
- [x] assignee가 본인으로 되어있고, label은 PR 주제에 맞게 추가했는가
- [x] description에 PR에 대해 구체적으로 설명했는가

2022-07-28 14:31 UTC, manudeli commented
> ### Issue Number
> 
> close: #54 #55 
> 
> ### 작업 내역
> 
> > 구현 내용 및 작업 했던 내역
> 
> - [x] 메인 인트로 UI
> - [x] 로그인 인트로 UI
> 
> ### 변경사항
> 
> - 카카오 로그인 버튼 기본 텍스트 삭제
> - 카카오 로그인 이미지로 대체
> 
> ### 참고사항
> 
> 메인 인트로 아래, 무한히 옆으로 움직이는 배너(?) 컴포넌트는 추후 작업합니다.
> [flicking](https://www.npmjs.com/package/@egjs/react-flicking) 라이브러리 참고하겠습니다. ㅎ.ㅎ
> ( 참고 아래 사진 )
> 
> ![스크린샷 2022-07-28 오후 10 38 43](https://user-images.githubusercontent.com/16275188/181519213-2c0c12b1-d03d-4fb6-9951-ba5a29995190.png)
> 
> ### Checklist
> 
> > PR 등록 전 확인할 점
> 
> - [x] PR 제목은 포맷과 내용 둘 다 알맞게 작성되었는가 (e.g., `feat(user): add login page`)
> - [x] assignee가 본인으로 되어있고, label은 PR 주제에 맞게 추가했는가
> - [x] description에 PR에 대해 구체적으로 설명했는가
> 

@Young-mason 형 swiper도 좋지만 flicking 꼭 써보면 좋겠어

스와이퍼 역할하는 라이브러리를 통일하면 좋을 거 같아서

2022-07-29 01:17 UTC, Young-mason commented
@manudeli 아 다른부분이랑 통일되는게 좋겠넹 ㅎㅎ 나도 방 메인부분 flicking으로 작업해볼게~

2022-07-29 11:03 UTC, manudeli requested changes

2022-07-29 11:03 UTC, manudeli commented on pages/login/index.tsx
> +            }}
이 props들이 내부로 들어가면 좋을 거 같다~
카카오로그인이 외부 상태에 따라서 변경되어야할 내용은 없을테니까 카카오로그인버튼을 외부 props를 전혀 안받게 하는 게 좋을 거 같아

2022-07-29 11:03 UTC, manudeli commented on pages/login/styled.tsx
> +`;
파일 외부로 빼는 게 재사용해야하는 이유가 아니라면 관리포인트가 많아지기 때문에 한파일로 합치면 좋을 거 같아

2022-07-29 11:03 UTC, manudeli commented on pages/login/index.tsx
> +import { StyledContainer, StyledHeader } from "./styled";
```suggestion
import * as S from "./styled";
```
파일로 뺄거라면 위 처럼 바꿔보면 어떨까?
```typescript
const Comp = () => {
  return <S.Container>
      <TopBar/>
    </S.Container>
}

```

사용하는 곳에서 어떤 게 styled만이고 어떤 게 domains/uis 컴포넌트인지 확실히 구분할 수 있게 될거야

2022-07-29 11:03 UTC, manudeli commented on pages/main/index.tsx
> +} from "./styled";
```suggestion
import  * as S from './styled'
```
위에서 코멘트 단 것과 같은 이유로 달았어

2022-07-29 11:03 UTC, manudeli commented on pages/login/index.tsx
> +              border: "none",
반응형을 생각해주면 좋을 거 같아
```suggestion
              display: 'block',
              background: "kakaocolor", // themeProvider에서 kakaoYellow라는 이름으로 뿌려주고 있으니 styled에서 theme을 받아와서 쓰면 될거야
              cursor: "pointer",
              border: "none",
```

theme/emotionTheme에 있으니 참고참고

2022-07-29 15:40 UTC, kor-Chipmunk commented on pages/login/styled.tsx
> +`;
[f05abaf](https://github.com/mash-up-kr/musily-web/pull/62/commits/f05abaf7af72b338653ab652a103c862ebb9862b) 커밋에 반영했습니다.

2022-07-29 15:40 UTC, kor-Chipmunk commented on pages/main/index.tsx
> +} from "./styled";
[511a58c](https://github.com/mash-up-kr/musily-web/pull/62/commits/511a58c6455b57aaf561277058171de7b9d25676) 커밋에 반영했습니다.

2022-07-29 15:41 UTC, kor-Chipmunk commented on pages/login/index.tsx
> +import { StyledContainer, StyledHeader } from "./styled";
[227ce79](https://github.com/mash-up-kr/musily-web/pull/62/commits/227ce792e16bcd8f7741d269f9b02a1e946eff8f) 커밋에 반영했습니다.

2022-07-29 15:41 UTC, kor-Chipmunk commented on pages/login/index.tsx
> +              border: "none",
[274562a](https://github.com/mash-up-kr/musily-web/pull/62/commits/274562a59a0e9e34ccc6ab43911ffa3b5b1fa03f) 커밋에 `width: "100%"` 으로 수정했습니다.

카카오 로그인 버튼 만들 때 PNG 로 안넣으면, 따로 카카오 로고(?) 같은 것도 직접 넣어줘야 할까요.

2022-07-29 15:42 UTC, kor-Chipmunk commented on pages/login/index.tsx
> +            }}
[d14c572](https://github.com/mash-up-kr/musily-web/pull/62/commits/d14c57280173a75f7787b75f43280ee1d2f382f2) 커밋에서 기본 스타일로 반영했습니다.

2022-07-29 23:34 UTC, manudeli commented on pages/login/index.tsx
> +              border: "none",
https://developers.kakao.com/docs/latest/ko/reference/design-guide#색상(color)
아마 이 디자인 가이드를 말하는 거 같은데 여기에서도 보면 알 수 있다시피 꼭 이걸 따라야하는 건 아니라고 나와있어

이미지라면 width가 100%라면 그대로 높이도 늘어날거고 상하좌우 비율이나 해상도에서 문제가 생길거야

그래서 로고와 텍스트조합으로 html을 재조합해주는게 필요하다고 생각해

2022-07-29 23:52 UTC, manudeli requested changes
S로 묶는 의미는 Styled를 포함하니까 Styled는 제거해주면 좋을 거 같아
카카오 로그인 디자인 가이드에도 나와있다시피 저 이미지를 그대로 써야할 필요는 없다고 생각해
디자인가이드에 맞추지만 우리 환경에 맞출 수 있는
-> 모바일 좌우사이즈 반응형 환경에 맞춰서 잘 늘어나고 줄어들 수 있는 버튼을 만들면 좋을 거 같아

2022-07-29 23:52 UTC, manudeli commented on pages/login/index.tsx
> +  `,
```suggestion
  Container: styled.div`
    display: flex;
    flex-direction: column;
    margin-top: 42px;
    gap: 40px;
  `,
  Header: styled.div`
    font-weight: 600;
    font-size: 24px;
    line-height: 34.8px;
    letter-spacing: -0.25px;
    color: white;
  `,
```

2022-07-29 23:52 UTC, manudeli commented on pages/login/index.tsx
> +        </S.StyledContainer>
```suggestion
        <S.Container>
          <S.Header>
            방을 만드려면<br></br>
            로그인이 필요해요
          </S.Header>
          <KakaoLoginButton
            restApiKey={
              process.env.NEXT_PUBLIC_KAKAO_APP_KEY_REST_API_KEY as string
            }
            redirectUri={
              process.env.NEXT_PUBLIC_KAKAO_LOGIN_REDIRECT_URI as string
            }
          ></KakaoLoginButton>
        </S.Container>
```

2022-07-29 23:52 UTC, manudeli commented on pages/main/index.tsx
> +        </S.StyeldForm>
```suggestion
        <S.Form onSubmit={onSubmit}>
          <S.InviteContainer>
            <S.RoomTextContainer>
              <S.RoomInputText
                type="text"
                onChange={(e) => setRoomTitle(e.target.value)}
              ></S.RoomInputText>
            </S.RoomTextContainer>
            <S.Spacer></S.Spacer>
            <S.Header>
              함께 만드는
              <br />
              모두의 플레이리스트
            </S.Header>
            <S.CreateRoomButton type="submit">
              방 만들기
            </S.CreateRoomButton>
            <S.Descripion>
              지금 바로 3초만에 만들어보세요!
            </S.Descripion>
          </S.InviteContainer>
        </S.Form>
```

2022-07-29 23:52 UTC, manudeli commented on pages/main/styled.tsx
> +`;
```suggestion
export const TopBarRightItem = styled.div`
  color: #007aff;
  font-weight: 700;
  font-size: 17px;
  font-height: 155%;
  letter-spacing: -0.478073px;

  display: flex;
  align-items: center;
`;

export const InviteContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 0 60px;
  gap: 6px;
`;

export const Form = styled.form`
  width: 100%;
  max-width: 100vw;
  min-height: 100vh;
  height: 100vh;
  min-height: 100vh;
  display: flex;
  align-items: center;
  flex-direction: column;
  justify-content: space-between;
  padding-top: 48px;
  padding-bottom: constant(safe-area-inset-bottom);
  padding-bottom: env(safe-area-inset-bottom);
`;

export const RoomTextContainer = styled.div`
  width: 100%;
  height: 45px;
  padding: 4px 8px;
  background-color: #333;
  border-radius: 7px;
`;

export const RoomInputText = styled.input`
  width: 100%;
  height: 100%;
  background-color: #333;
  border: none;
  color: white;
  font-size: 26px;
`;

export const Spacer = styled.div`
  width: 100%;
  height: 2px;
`;

export const Header = styled.div`
  font: "Apple SD Gothic Neo";
  font-weight: 700;
  font-size: 26px;
  color: white;
  text-align: center;
  line-height: 43.2px;
`;

export const CreateRoomButton = styled.button`
  margin-top: 58px;
  width: 149px;
  height: 51px;
  background-color: #007aff;
  border-radius: 15px;
  color: white;
  font-weight: 700;
  font-size: 20px;
  line-height: 23.87px;
  letter-spacing: -0.45px;
  text-align: center;
  border: none;
  cursor: pointer;
`;

export const Descripion = styled.span`
  margin-top: 18px;
  font-size: 14px;
  line-height: 22.4px;
  color: #d9d9d9;
  font-family: "Pretendard";
  font-style: normal;
  font-weight: 500;
`;
```

2022-07-29 23:52 UTC, manudeli commented on pages/main/styled.tsx
> +`;
```suggestion
export const TopBarRightItem = styled.div`
  color: #007aff;
  font-weight: 700;
  font-size: 17px;
  font-height: 155%;
  letter-spacing: -0.478073px;

  display: flex;
  align-items: center;
`;

export const InviteContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 0 60px;
  gap: 6px;
`;

export const Form = styled.form`
  width: 100%;
  max-width: 100vw;
  min-height: 100vh;
  height: 100vh;
  min-height: 100vh;
  display: flex;
  align-items: center;
  flex-direction: column;
  justify-content: space-between;
  padding-top: 48px;
  padding-bottom: constant(safe-area-inset-bottom);
  padding-bottom: env(safe-area-inset-bottom);
`;

export const RoomTextContainer = styled.div`
  width: 100%;
  height: 45px;
  padding: 4px 8px;
  background-color: #333;
  border-radius: 7px;
`;

export const RoomInputText = styled.input`
  width: 100%;
  height: 100%;
  background-color: #333;
  border: none;
  color: white;
  font-size: 26px;
`;

export const Spacer = styled.div`
  width: 100%;
  height: 2px;
`;

export const Header = styled.div`
  font: "Apple SD Gothic Neo";
  font-weight: 700;
  font-size: 26px;
  color: white;
  text-align: center;
  line-height: 43.2px;
`;

export const CreateRoomButton = styled.button`
  margin-top: 58px;
  width: 149px;
  height: 51px;
  background-color: #007aff;
  border-radius: 15px;
  color: white;
  font-weight: 700;
  font-size: 20px;
  line-height: 23.87px;
  letter-spacing: -0.45px;
  text-align: center;
  border: none;
  cursor: pointer;
`;

export const Descripion = styled.span`
  margin-top: 18px;
  font-size: 14px;
  line-height: 22.4px;
  color: #d9d9d9;
  font-family: "Pretendard";
  font-style: normal;
  font-weight: 500;
`;
```

2022-07-29 23:52 UTC, manudeli commented on pages/main/styled.tsx
> +`;
```suggestion
export const TopBarRightItem = styled.div`
  color: #007aff;
  font-weight: 700;
  font-size: 17px;
  font-height: 155%;
  letter-spacing: -0.478073px;

  display: flex;
  align-items: center;
`;

export const InviteContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 0 60px;
  gap: 6px;
`;

export const Form = styled.form`
  width: 100%;
  max-width: 100vw;
  min-height: 100vh;
  height: 100vh;
  min-height: 100vh;
  display: flex;
  align-items: center;
  flex-direction: column;
  justify-content: space-between;
  padding-top: 48px;
  padding-bottom: constant(safe-area-inset-bottom);
  padding-bottom: env(safe-area-inset-bottom);
`;

export const RoomTextContainer = styled.div`
  width: 100%;
  height: 45px;
  padding: 4px 8px;
  background-color: #333;
  border-radius: 7px;
`;

export const RoomInputText = styled.input`
  width: 100%;
  height: 100%;
  background-color: #333;
  border: none;
  color: white;
  font-size: 26px;
`;

export const Spacer = styled.div`
  width: 100%;
  height: 2px;
`;

export const Header = styled.div`
  font: "Apple SD Gothic Neo";
  font-weight: 700;
  font-size: 26px;
  color: white;
  text-align: center;
  line-height: 43.2px;
`;

export const CreateRoomButton = styled.button`
  margin-top: 58px;
  width: 149px;
  height: 51px;
  background-color: #007aff;
  border-radius: 15px;
  color: white;
  font-weight: 700;
  font-size: 20px;
  line-height: 23.87px;
  letter-spacing: -0.45px;
  text-align: center;
  border: none;
  cursor: pointer;
`;

export const Descripion = styled.span`
  margin-top: 18px;
  font-size: 14px;
  line-height: 22.4px;
  color: #d9d9d9;
  font-family: "Pretendard";
  font-style: normal;
  font-weight: 500;
`;
```

2022-07-29 23:52 UTC, manudeli commented on pages/main/styled.tsx
> +`;
```suggestion
export const TopBarRightItem = styled.div`
  color: #007aff;
  font-weight: 700;
  font-size: 17px;
  font-height: 155%;
  letter-spacing: -0.478073px;

  display: flex;
  align-items: center;
`;

export const InviteContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 0 60px;
  gap: 6px;
`;

export const Form = styled.form`
  width: 100%;
  max-width: 100vw;
  min-height: 100vh;
  height: 100vh;
  min-height: 100vh;
  display: flex;
  align-items: center;
  flex-direction: column;
  justify-content: space-between;
  padding-top: 48px;
  padding-bottom: constant(safe-area-inset-bottom);
  padding-bottom: env(safe-area-inset-bottom);
`;

export const RoomTextContainer = styled.div`
  width: 100%;
  height: 45px;
  padding: 4px 8px;
  background-color: #333;
  border-radius: 7px;
`;

export const RoomInputText = styled.input`
  width: 100%;
  height: 100%;
  background-color: #333;
  border: none;
  color: white;
  font-size: 26px;
`;

export const Spacer = styled.div`
  width: 100%;
  height: 2px;
`;

export const Header = styled.div`
  font: "Apple SD Gothic Neo";
  font-weight: 700;
  font-size: 26px;
  color: white;
  text-align: center;
  line-height: 43.2px;
`;

export const CreateRoomButton = styled.button`
  margin-top: 58px;
  width: 149px;
  height: 51px;
  background-color: #007aff;
  border-radius: 15px;
  color: white;
  font-weight: 700;
  font-size: 20px;
  line-height: 23.87px;
  letter-spacing: -0.45px;
  text-align: center;
  border: none;
  cursor: pointer;
`;

export const Descripion = styled.span`
  margin-top: 18px;
  font-size: 14px;
  line-height: 22.4px;
  color: #d9d9d9;
  font-family: "Pretendard";
  font-style: normal;
  font-weight: 500;
`;

```

2022-07-31 15:00 UTC, swimjiy reviewed
나머지는 종현이가 리뷰 잘 남겨준 것 같아서 폰트 관련해서만 코멘트 남겼어 고생했어!

2022-07-31 15:00 UTC, swimjiy commented on pages/main/styled.tsx
> +  font: "Apple SD Gothic Neo";
중간중간 폰트로 `Apple SD Gothic Neo`가 들어가 있는데, 우리 기본으로 설정해놓은 폰트가 따로 있어서 이것들은 빼주면 좋을 것 같아!

2022-07-31 15:00 UTC, swimjiy commented on pages/main/styled.tsx
> +  font-family: "Pretendard";
`font-family: "Pretendard";` 이렇게 작성되어 있는 코드들도 빼주면 좋을 것 같아 만약 span태그에 폰트 적용 따로 안되어 있어서 추가해준 거라면 내가 `global.css` 에 추가해 놓을게!

2022-08-02 14:08 UTC, kor-Chipmunk commented
@manudeli @swimjiy 폰트 수정하구, Styled 컴포넌트 명 Styled 뺀 걸로 수정했습니다!
카카오 로그인은 따른 PR 로 올릴게욥!

2022-08-02 14:54 UTC, manudeli approved these changes
좋아요 일단 Approve 하고 추가 개선사항은 후에 개선해나가자

2022-08-02 15:10 UTC, swimjiy approved these changes
굿굿 반영하느라 고생했어!

2022-08-03 01:49 UTC, Young-mason approved these changes
LGTM 입니다!

2022-08-03 11:58 UTC, merged