feat: setup recoil and react query
mash-up-kr/muzily-web pull request #68
Opened 2022-07-29 05:43 UTC by swimjiy

### Issue Number

close: #50 #67 

### 작업 내역

> 구현 내용 및 작업 했던 내역

- [x] react-query, recoil 기본 구조 세팅
- [x] api 코어 로직 추가
- [x] `useMemberQuery`, `usePutMemberMutation` 커스텀 훅 추가
- [x] 예시 페이지 작성 

자세한 디렉토리 구조 및 사용 방법은 [wiki 페이지](https://github.com/mash-up-kr/musily-web/wiki/001.-Recoil,-React-query-%EA%B5%AC%EC%A1%B0-%EC%84%A4%EB%AA%85-%EB%B0%8F-%EC%82%AC%EC%9A%A9-%EB%B0%A9%EB%B2%95) 에 작성해 두었으니 참고해 주세요.

### PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- 에러 핸들링을 우선 console.error()로 했는데, 추가로 핸들링 할만한 게 어떤게 있을지
- 이 세팅에 맞춰 react query, recoil을 사용할 수 있을지 (복잡하진 않은지)

### Checklist

> PR 등록 전 확인할 점

- [x] PR 제목은 포맷과 내용 둘 다 알맞게 작성되었는가 (e.g., `feat(user): add login page`)
- [x] assignee가 본인으로 되어있고, label은 PR 주제에 맞게 추가했는가
- [x] description에 PR에 대해 구체적으로 설명했는가

2022-07-30 03:25 UTC, Young-mason approved these changes
LGTM! 폴더구조도 괜찮은거같아~ 

머지해주시면 사용해보면서 피드백 공유할게요

2022-07-30 05:29 UTC, manudeli requested changes
지영 수고 많았어

react-query recoil같은 코어를 담당한 만큼 한번 의존되기 시작하면 변경사항이 많아지니 고려해볼 부분을 적어봣어! 체크 한번 부탁해

2022-07-30 05:29 UTC, manudeli commented on api/core/index.ts
> +};
이 부분 너무 맘에 든다
이렇게 쓰는 거 다른 곳에서도 사용하고 싶다.

2022-07-30 05:29 UTC, manudeli commented on api/core/index.ts
> +};
tokenKey는 환경변수기 때문에 빌드타임외에는 변하지 않을 거기 때문에 함수를 실행할 때마다 매번 선언하는 거보다 외부에 선언해두고 있는 게 성능적으로 더 좋을 거 같아

```suggestion

const tokenKey = process.env.NEXT_PUBLIC_LOCAL_TOKEN_KEY as string;

const handleRequest = (config: AxiosRequestConfig): AxiosRequestConfig => {
  const localStorageToken: string | null = JSON.parse(
    localStorage.getItem(tokenKey) ?? "null"
  );

  return {
    ...config,
    headers: {
      ...config.headers,
      Authorization: `Bearer ${localStorageToken}`,
    },
  };
};
```

2022-07-30 05:29 UTC, manudeli commented on api/core/index.ts
> +  };
url을 첫 번째 인자로 받게하면 위계가 더 있는 http가 될 수 있을 거 같아서
그럼 이제 이렇게 되는 거지
http / GET / url / headers

이렇게 하면 어떨까?

### 제안
```suggestion
const createApiMethod =
  (_axiosInstance: AxiosInstance, method: Method) =>
  (
    url: AxiosRequestConfig["url"],
    config: Omit<AxiosRequestConfig, "url">
  ): Promise<any> => {
    return _axiosInstance({
      ...handleRequest({ url, ...config }),
      method,
    })
      .then((res) => handleResponse(res))
      .catch((err) => {
        throw new Error(err);
      });
  };
```

### 사용법
```typescript
import http from "~/api/core";
import type { Member, PutMemberReq } from "~/types/members";

export const getMember = (): Promise<Member> => http.get("/members", {});

export const putMember = (memberReq: PutMemberReq): Promise<Member> =>
  http.put("/members", {
    data: memberReq,
  });
```

이렇게 하면 정말 내가 꿈꾸던 아름다운 interface가 되어버린다... 이거 회사에 들고 가고 싶다..

2022-07-30 05:29 UTC, manudeli commented on api/core/index.ts
> +});
axios로 응답을 가공하고 싶다면
interceptor로 요청과 응답 때 가로채서 어떠한 처리를 할 수 있어

아래 링크를 참고하면 좋을 거 같아
### 🔗 axios interceptor 
https://axios-http.com/kr/docs/interceptors

![image](https://user-images.githubusercontent.com/61593290/181875482-92ecccaf-6d34-4fa9-818b-a53c2c523c94.png)

2022-07-30 05:29 UTC, manudeli commented on consts/react-query/index.ts
> +  roomsById: (roomId: number) => ["rooms", roomId],
호우 이렇게도 가능하겠구만...

2022-07-30 05:29 UTC, manudeli commented on consts/api/index.ts
> +};
as const 로 불필요한 타입을 삭제하고 타입을 더 구체화 할 수 있을 거 같아
현재는 모든 value는 string일 테니까
더 확실히 해보면 좋을 거 같아

```suggestion
export const HTTP_METHOD = {
  GET: "get",
  POST: "post",
  PUT: "put",
  PATCH: "patch",
  DELETE: "delete",
} as const;

export const HTTP_ERROR = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
} as const
```

2022-07-30 05:29 UTC, manudeli commented on hooks/api/core/index.ts
> +}
오 좋은 거 같은데? 에러처리가 console.error로 되기도 하지만 나중에 외부에서 주입하고 싶으면 options에 추가하면 되니까~

2022-07-30 05:29 UTC, manudeli commented on pages/_app.tsx
> +        <ReactQueryDevtools initialIsOpen={false} position="bottom-right" />
내가 하려고 했는데 해줘서 고맙구만 issue도 assignee 옮겨놧어

2022-07-30 05:29 UTC, manudeli commented on pages/test/react-query-recoil/index.tsx
> +  });
요청에 필요한 타입은 언제든 변경될 수 있기 때문에 이렇게 하면 더 좋을 거 같아

이렇게 되면 PutMemeberReq은 해당 api에 한 곳에서만 필요한 타입이 되니 삭제해주는 게 좋은 interface가 될 거 같아

```suggestion
  const [value, setValue] = useState<Pick<Memeber, 'nickname' | 'profileUrl'>>({
    nickname: "",
    profileUrl: "",
  });
```

2022-07-30 05:29 UTC, manudeli commented on types/members/index.ts
> +}
이 타입은 putMember 와 관련이 있고 그 함수에서만 쓰이는 타입이기 때문에 응집성을 높이기 위해 따로 다른 디렉토리에 interface를 정의 하지 않고

해당 함수의 인자에 직접 정의하는게 좋다고 생각해
```typescript
export const putMember = (params: Pick<Member, 'nickname' | 'profileUrl'>): Promise<Member> =>
  http.put("/members", {
    data: memberReq,
  });
```

만약 이 타입이 외부에서 꼭 필요한 상황이라면 만약에 Member의 타입이 변경되더라도 더 관리하기 쉬워지지 않을까 싶어
```typescript
type MemberPutReqFirstParam = Parameter<typeof putMember>[0]
```

2022-07-31 15:42 UTC, swimjiy commented on consts/api/index.ts
> +};
좋네 반영했어!

2022-07-31 15:43 UTC, swimjiy commented on api/core/index.ts
> +};
그치 다른팀 프론트 코드 구경하다 괜찮아보여서 참고했어ㅋㅋㅋ

2022-07-31 15:44 UTC, swimjiy commented on api/core/index.ts
> +};
좋은 의견이야 반영했어!

2022-07-31 15:52 UTC, swimjiy commented on api/core/index.ts
> +  };
오 선언적이고 좋네👍  반영했구, 추가로 적어준 사용방법 보니까 이제부턴 config가 없을 확률이 있게 되니 optional하게 가져가도 좋을 것 같아서 `config?: Omit<AxiosRequestConfig, "url">` 이렇게 작업했어!

2022-07-31 15:55 UTC, swimjiy commented on api/core/index.ts
> +});
오 요런 것도 가능하구나. 이걸 사용해서 에러 핸들링 같은것도 해볼 수 있으려나🤔

2022-07-31 15:56 UTC, swimjiy commented on hooks/api/core/index.ts
> +}
다행이네 그럼 일단 요정도로 해놓을게!

2022-07-31 16:09 UTC, swimjiy commented on types/members/index.ts
> +}
안그래도 내용이 중복되어 고민하던 부분이었는데 괜찮은 것 같다👍 위에 코멘트 달아준 거랑 같이 업데이트 했어!

2022-07-31 16:09 UTC, swimjiy commented on pages/test/react-query-recoil/index.tsx
> +  });
아래 코멘트 작업하면서 같이 업데이트했어!

2022-07-31 16:21 UTC, manudeli approved these changes
코멘트 적지않게 달아놨는데 반영하느라 수고 많았어! 이 이상의 문제가 있다면 그때 다시 생각해보자

2022-08-01 05:28 UTC, merged