Feature/#49 add music
mash-up-kr/muzily-web pull request #70
Opened 2022-07-29 15:41 UTC by Young-mason

### Issue Number

close: #69 

### 작업 내역

> 구현 내용 및 작업 했던 내역

연속적으로 작업하다보니 3가지 정도 작업을 pr 하나로 묶어서 올립니다

- 곡 추가하기 > 유튜브 링크에서 id 추출하는 기능 개선 (#49)
- 방 메인화면 플레이리스트 카드, 재생화면 카드 개선
- 플레이리스트 순서변경 기능추가 (dnd) (#69)

![dnd](https://user-images.githubusercontent.com/61150435/181793786-bd9801bf-ca57-4a99-912b-5c70e712a72d.gif)

### 변경사항

- 의존성 목록: react-dnd,  react-dnd-backend

### PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

 - #49 는 id 추출 후 곡 상세정보 가져오는 api 연결까지 완료했고,  이후에는 받아온 정보 기반으로 곡 추가 요청을 보내야하는데 추후 작업할게요!
 - #69  는 일단 작동하는 수준으로 1차적으로 작업했고, 추후에 api 붙이면서 UI쪽도 조금더 개선해보겟습니당 (잔잔바리 버그들 있을수있음 ㅎ)
- #68 요거 머지되면 recoil 활용해서 상태관리 전반적으로 리팩토링한번 할게요, 현재 props drilling 이 좀 있습니다

### Checklist

> PR 등록 전 확인할 점

- [ ] PR 제목은 포맷과 내용 둘 다 알맞게 작성되었는가 (e.g., `feat(user): add login page`)
- [ ] assignee가 본인으로 되어있고, label은 PR 주제에 맞게 추가했는가
- [ ] description에 PR에 대해 구체적으로 설명했는가

2022-07-30 00:22 UTC, manudeli requested changes
모바일 퍼스트 디자인이라 터치 이벤트에 대한 대응은 꼭 해야할 거 같아
형 우리 framer-motion을 쓰고 있으니까 충분히 이걸 구현 할 수 있을 거 같은데 시도해보면 좋을 거 같아

## 모바일+PC 모두가능한 드래그앤드롭 예시 코드
https://codesandbox.io/s/framer-motion-drag-to-reorder-pkm1k?resolutionWidth=320&resolutionHeight=675

나머지 코멘트는 세부 디자인이랑 코드 일관성이 조금 다른 거 같아보여서 달았어

2022-07-30 00:22 UTC, manudeli commented on components/domains/PlaylistScreen/MusicItemCard.tsx
> +    border-left: 0.7px solid rgba(255, 255, 255, 0.08);
```suggestion
    border: 1px solid rgba(255, 255, 255, 0.08);
```

### 피그마
![image](https://user-images.githubusercontent.com/61593290/181861942-0261b4ce-042a-4bd6-be96-e90d7b627124.png)

### 크롬 개발자도구
![image](https://user-images.githubusercontent.com/61593290/181861894-03b114c0-fe3e-4319-aea6-7e57cd0254f0.png)

2022-07-30 00:22 UTC, manudeli commented on components/domains/PlaylistScreen/MusicItemCard.tsx
> +    border-right: 1px solid rgba(255, 255, 255, 0.08);
```suggestion
    border: 1px solid rgba(255, 255, 255, 0.08);
```

2022-07-30 00:22 UTC, manudeli commented on components/domains/PlaylistScreen/MusicItemCard.tsx
> +    background-color: ${(p) => (p.active ? "#fff" : "#007aff")};
```suggestion
    background-color: ${({ active }) => (active ? "#fff" : "#007aff")};
```

2022-07-30 00:22 UTC, manudeli commented on components/domains/PlaylistScreen/index.tsx
> +              item={el}
범용적인 item보다 더 좋은 props interface는 없을까? 이 컴포넌트를 사용하는 사람이 외부에서 봤을 때 MusicItemCard에 item이라 이해하기 어려운 거 같아

2022-07-30 00:22 UTC, manudeli commented on components/domains/PlaylistScreen/index.tsx
>  `;
여기도 S 객체로 묶어주면 좋겠다

2022-07-30 03:50 UTC, Young-mason commented on components/domains/PlaylistScreen/MusicItemCard.tsx
> +    border-left: 0.7px solid rgba(255, 255, 255, 0.08);
땡큐 수정완료!

2022-07-30 03:53 UTC, Young-mason commented on components/domains/PlaylistScreen/MusicItemCard.tsx
> +    background-color: ${(p) => (p.active ? "#fff" : "#007aff")};
코드 중복이 생기는 등 필요한 경우가 아니라면 destructuring을 잘 안하는 편이야 ㅋㅋ 
요거 바꾸게되면 수정할 부분이 많아서 일단 넘겻어여, 참고할게 땡큐!

2022-07-30 03:53 UTC, Young-mason commented on components/domains/PlaylistScreen/index.tsx
>  `;
수정완료!

2022-07-30 03:54 UTC, Young-mason commented on components/domains/PlaylistScreen/index.tsx
> +              item={el}
음 List에 들어가는 Item 이라서 이해하기 어렵다는 생각은 안했는데, 더 괜찮은 네이밍 있다면 공유부탁해!

2022-07-30 03:54 UTC, Young-mason commented on components/domains/PlaylistScreen/MusicItemCard.tsx
> +    border-right: 1px solid rgba(255, 255, 255, 0.08);
수정완료!

2022-07-30 03:57 UTC, Young-mason commented
@manudeli 
모바일 대응을 안했었네~  일단 react-dnd 에서 제공하는 [TouchBackend api](https://react-dnd.github.io/react-dnd/docs/backends/touch) 에서 모바일에서 기능 동작 하게 해놨어
모션같은경우 지금은 우선순위라고 생각하지 않아서 일단 UT 전까지 다른 기능들 프로토타이핑 완료된 이후에 작업할게,
공유해준 프레이머 모션이 깔끔하고 좋아보인당 ㅋㅋ

2022-07-30 04:12 UTC, manudeli commented on components/domains/PlaylistScreen/index.tsx
> +              item={el}
domain 데이터를 ui 컴포넌트와 분리해주면 더 재활용할 수 있는 컴포넌트가 될 거 같아
music데이터는 해당 ListItem으로 주입해주고
ui와 domain을 분리한다면 이 listItem은 다른 곳에서도 활용할 수 있게 되니까 list는 다른 곳에서도 많이 쓰이니까
일단 approve하고 다음에 리팩토링하면 좋을 거 같아

아래는 한재엽님 발표중에 이 내용이랑 관련된 내용인 도메인 분리하기 섹션에서부터 영상 볼 수 있게 링크 걸어두었어

### [🔗 도메인 분리하기 in 토스ㅣSLASH 22 - Effective Component 지속 가능한 성장과 컴포넌트](https://youtu.be/fR8tsJ2r7Eg?t=919)

2022-07-30 04:26 UTC, manudeli commented on pages/rooms/[roomId]/index.tsx
> +          videoId={currentMusic?.id}
YouTube에서 videoId는 optional이 아니면 더 좋을 거 같아
videoId가 없을때 youtube 플레이어에서는 아무것도 없어야 하니까 undefined를 넣을 수 있으면 안될 거 같아서~

```typescript
        {currentMusic && <YouTube
          id="iframe"
          videoId={currentMusic.id}
          opts={{
            width: 300,
            height: 200,
            playerVars: {
              autoplay: 1,
              controls: 1,
            },
          }}
          onPlay={() => setIsPlaying(true)}
          onPause={() => setIsPlaying(false)}
          onReady={(event) => {
            setPlayer(event.target);
            event.target.playVideo();
          }}
          onEnd={() => {
            if (playingIndex === VIDEO_LIST.length - 1) {
              return alert("끝!!");
            }
            setPlayingIndex((prev) => prev + 1);
          }}
        />}
```

2022-07-30 04:36 UTC, manudeli approved these changes
우선 approve했어
터치가 기능이 되기는 하는데 터치로 목록 순서 바꾸는 건 바꾸고 있는 건지 아닌지 알기가 어려워보여
우리는 모바일 퍼스트니까 나중에라도 반영해주면 좋겠다

2022-07-30 04:44 UTC, manudeli requested changes

2022-07-30 04:44 UTC, manudeli commented on package.json
> +    "react-dnd-touch-backend": "^16.0.1",
yarn을 쓰기 때문에 package-lock.json은 삭제 해야겠다!

2022-07-30 04:46 UTC, manudeli requested changes
yarn을 쓰기 때문에 package-lock.json은 삭제해야겠다

2022-07-31 15:17 UTC, swimjiy approved these changes
되게 많이 작업했네 고생했어! 마이너한 코멘트 하나만 달았습니당

2022-07-31 15:17 UTC, swimjiy commented on contexts/MemberInfo/index.tsx
> +  // }
여기 혹시 테스트 때문에 임시로 주석 처리한걸까?? 맞다면 풀어놓는게 좋을 것 같아서!

2022-08-01 01:47 UTC, Young-mason commented on contexts/MemberInfo/index.tsx
> +  // }
아고 고마워~ 다시 살렷어!

2022-08-01 01:47 UTC, Young-mason commented on pages/rooms/[roomId]/index.tsx
> +          videoId={currentMusic?.id}
수정했어~ 땡큐!

2022-08-01 01:48 UTC, merged